inherit_gem:
  bixby: bixby_default.yml

Style/MutableConstant:
  Enabled: true
  Exclude:
    - 'lib/geo_compile/registry.rb'

Style/ClassAndModuleCamelCase:
  Enabled: true
  Exclude:
    - 'lib/geo_compile/format_*/*.rb'

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/**/*.rb'
    - '**/*.gemspec'